# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eebb13bbcc060c9a102975c141aee940b8279e97c923caf6f28959220d3595c8f635a56851440ceee6484a8a94dd38bfbfe2a1307728a0806e6ee7f381edba33

test:
  secret_key_base: 09997fe5a1b772ac4525e7ad42a17099f5c0cb76c4a2c8b05a56b387a414871513fe1b3b2dbb8baad6fd7168e12dbe365dfd7b9015240d4e7a9229417a4e99c4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
